import Head from "next/head";
import Button from '@/components/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Drive Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello Google Drive</h1>
        <Button style="btn-primary" title="Sing Up"/>
      </main>
    </>
  );
}
